---
- name: Copy PKI key and certificate
  ansible.builtin.copy:
    src: "../../../../../tls/{{ item }}"
    dest: "/home/ubuntu/{{ item }}"
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  loop:
    - "{{ inventory_hostname }}-key.pem"
    - "{{ inventory_hostname }}.pem"

- name: Copy kubeconfig
  ansible.builtin.copy:
    src: "../../../../../kubeconfig/{{ item }}"
    dest: "/home/ubuntu/{{ item }}"
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  loop:
    - "{{ inventory_hostname }}.kubeconfig"
    - kube-proxy.kubeconfig
