- name: Install runc (1/1) - Download binary
  ansible.builtin.get_url:
    url: https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.amd64
    dest: /usr/local/bin/runc
    mode: '0755'
  become: true
