- name: Install kube-proxy (1/6) - Create configuration directory
  ansible.builtin.file:
    path: /var/lib/kube-proxy
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Install kube-proxy (2/6) - Upload kubeconfig
  ansible.builtin.copy:
    src: ../../../../kubeconfig/kube-proxy.kubeconfig
    dest: /var/lib/kube-proxy/kubeconfig
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Install kube-proxy (3/6) - Upload config
  ansible.builtin.template:
    src: kube-proxy-config.yaml.j2
    dest: /var/lib/kube-proxy/kube-proxy-config.yaml
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Install kube-proxy (4/6) - Download binary
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64/kube-proxy
    dest: /usr/local/bin/kube-proxy
    mode: '0755'
  become: true

- name: Install kube-proxy (5/6) - Copy systemd unit file
  ansible.builtin.copy:
    src: kube-proxy.service
    dest: /etc/systemd/system/kube-proxy.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Install kube-proxy (6/6) - Start the service
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: kube-proxy
  become: true
  notify:
    - Systemd daemon_reload
