- name: Install kubelet (1/8) - Create data directories
  ansible.builtin.file:
    path: /var/lib/{{ item }}
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true
  loop:
    - kubelet
    - kubernetes

- name: Install kubelet (2/8) - Upload certificates and keys
  ansible.builtin.copy:
    src: ../../../../tls/{{ item }}
    dest: /var/lib/kubelet/{{ item }}
    owner: root
    group: root
    mode: '0644'
  become: true
  loop:
    - "{{ inventory_hostname }}.pem"
    - "{{ inventory_hostname }}-key.pem"

- name: Install kubelet (3/8) - Upload kubeconfig
  ansible.builtin.copy:
    src: ../../../../kubeconfig/{{ inventory_hostname }}.kubeconfig
    dest: /var/lib/kubelet/kubeconfig
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Install kubelet (4/8) - Upload certificate for kubernetes
  ansible.builtin.copy:
    src: ../../../../tls/ca.pem
    dest: /var/lib/kubernetes/ca.pem
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Install kubelet (5/8) - Upload config file
  ansible.builtin.template:
    src: kubelet-config.yaml.j2
    dest: /var/lib/kubelet/kubelet-config.yaml
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Install kubelet (6/8) - Download binary
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64/kubelet
    dest: /usr/local/bin/kubelet
    mode: '0755'
  become: true

- name: Install kubelet (7/8) - Copy systemd unit file
  ansible.builtin.copy:
    src: kubelet.service
    dest: /etc/systemd/system/kubelet.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Install kubelet (8/8) - Start service
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: kubelet
  become: true
  notify:
    - Systemd daemon_reload
