- name: Install dependencies (1/3) - Install cocat
  ansible.builtin.apt:
    name:
      - socat
    state: present
    update_cache: true
  become: true

- name: Install dependencies (2/3) - Install ipset
  ansible.builtin.apt:
    name:
      - ipset
    state: present
    update_cache: true
  become: true

- name:  Install dependencies (3/3) - Install conntrack
  ansible.builtin.apt:
    name:
      - conntrack
    state: present
    update_cache: true
  become: true
