- name: Install containerd (1/5) - Unpack the binaries
  ansible.builtin.unarchive:
    src: https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz 
    dest: /bin/
    remote_src: yes
    mode: '0755'
    extra_opts: ['--strip-components=1', '--show-stored-names']
  become: true

- name: Install containerd (2/5) - Create configuration directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Install containerd (3/5) - Copy configuration file
  ansible.builtin.copy:
    src: containerd.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Install containerd (4/5) - Copy systemd unit file
  ansible.builtin.copy:
    src: containerd.service
    dest: /etc/systemd/system/containerd.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Install containerd (5/5) - Start the service
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: containerd
  become: true
  notify:
    - Systemd daemon_reload
