- name: Configure kube-proxy (1/3) - Create configuration directory
  ansible.builtin.file:
    path: /var/lib/kube-proxy
    state: directory
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Configure kube-proxy (2/3) - Upload kube-proxy kubeconfig
  ansible.builtin.copy:
    src: ../../../../kubeconfig/kube-proxy.kubeconfig
    dest: /var/lib/kube-proxy/kubeconfig
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Configure kube-proxy (3/3) - Upload kube-proxy config
  ansible.builtin.template:
    src: kube-proxy-config.yaml.j2
    dest: /var/lib/kube-proxy/kube-proxy-config.yaml
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Download kube-proxy binary (1/1) - Provides high level network features including load balancing and service discovery between pods
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64/kube-proxy
    dest: /usr/local/bin/kube-proxy
    mode: '0755'
  become: true

- name: Configure kube-proxy service (1/2) - Copy kube-proxy systemd unit file
  ansible.builtin.copy:
    src: kube-proxy.service
    dest: /etc/systemd/system/kube-proxy.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Configure kube-proxy service (2/2) - Enable and start the kube-proxy service
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: kube-proxy
  become: true
  notify:
    - Systemd daemon_reload
