- name: Install CNI plugins (1/3) - Create binary and configuration directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true
  loop:
    - /etc/cni
    - /etc/cni/net.d
    - /opt/cni
    - /opt/cni/bin

- name: Install CNI plugins (2/3) - Unpack binaries
  ansible.builtin.unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v{{ cni_version }}/cni-plugins-linux-amd64-v{{ cni_version }}.tgz
    dest: /opt/cni/bin/
    remote_src: yes
    mode: '0755'
  become: true
  ignore_errors: true

- name: Install CNI plugins (3/3) - Copy configuration file
  ansible.builtin.template:
    src: 10-containerd-net.conflist.j2
    dest: /etc/cni/net.d/10-containerd-net.conflist
    owner: root
    group: root
    mode: '0644'
  become: true
