- name: Install crictl (1/1) - Download and unpack binaries
  ansible.builtin.unarchive:
    src: https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ crictl_version }}/crictl-v{{ crictl_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0755'
    owner: 'root'
    group: 'root'
    creates: /usr/local/bin/crictl
  become: true
  ignore_errors: true
