- name: |
    Create directories
    DESC [Directories to store configuration files (net.d) and binaries (bin) respectively]
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0644'
    owner: root
    group: root
  become: true
  loop:
    - /etc/cni/net.d
    - /opt/cni/bin

- name: Download CNI plugins release tarball
  ansible.builtin.get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz
    dest: /tmp
    mode: '0644'
  become: true

- name: Unpack CNI binaries
  ansible.builtin.unarchive:
    src: /tmp/cni-plugins-linux-amd64-v0.9.1.tgz
    dest: /opt/cni/bin/
    remote_src: yes
    mode: '0755'
  become: true

- name: |
    Configure CNI bridge network
    DESC [Connects all containers running on a single host to a virtual switch (the bridge)]
  ansible.builtin.template:
    src: 10-bridge.conf.j2
    dest: /etc/cni/net.d/10-bridge.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: |
    Configure CNI loopback network
    DESC [Facilitates communication over localhost]
  ansible.builtin.copy:
    src: 99-loopback.conf
    dest: /etc/cni/net.d/99-loopback.conf
    owner: root
    group: root
    mode: '0644'
  become: true
