---
# tasks file for kubernetes-worker-node
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - socat
      - conntrack
      - ipset
    state: present
    update_cache: true
  become: true

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: |
    swapoff -a

- name: Disable SWAP on boot since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0644'
    owner: root
    group: root
  become: true
  loop:
    - /etc/cni/net.d
    - /opt/cni/bin
    - /var/lib/kubelet
    - /var/lib/kube-proxy
    - /var/lib/kubernetes
    - /var/run/kubernetes

- name: Download and unpack kubernetes worker components (1/5)
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64/{{ item }}
    dest: /usr/local/bin/{{ item }}
    mode: '0755'
  become: true
  loop:
    - kube-proxy
    - kubelet
    - kubectl

- name: Download and unpack kubernetes worker components (2/5)
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: /tmp
    mode: '0644'
  become: true
  loop:
    - https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.21.0/crictl-v1.21.0-linux-amd64.tar.gz
    - https://github.com/opencontainers/runc/releases/download/v1.0.0-rc93/runc.amd64
    - https://github.com/containernetworking/plugins/releases/download/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz
    - https://github.com/containerd/containerd/releases/download/v1.4.4/containerd-1.4.4-linux-amd64.tar.gz 

- name: Download and unpack kubernetes worker components (3/5)
  ansible.builtin.file:
    path: /tmp/containerd
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Download and unpack kubernetes worker components (4/5)
  ansible.builtin.unarchive:
    src: /tmp/{{ item.src }}
    dest: "{{ item.dest }}"
    remote_src: yes
    mode: '0755'
  become: true
  loop:
    - { src: 'cni-plugins-linux-amd64-v0.9.1.tgz',  dest: '/opt/cni/bin/' }
    - { src: 'containerd-1.4.4-linux-amd64.tar.gz', dest: '/tmp/containerd/' }
    - { src: 'crictl-v1.21.0-linux-amd64.tar.gz',   dest: '/tmp/' }
    - { src: 'cni-plugins-linux-amd64-v0.9.1.tgz',  dest: '/opt/cni/bin/' }
    - { src: 'containerd-1.4.4-linux-amd64.tar.gz', dest: '/bin/' }

- name: Download and unpack kubernetes worker components (5/5)
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  become: true
  loop:
    - { src: '/tmp/runc.amd64',                             dest: '/usr/local/bin/runc' }
    - { src: '/tmp/crictl',                                 dest: '/usr/local/bin/crictl' }
    - { src: '/tmp/containerd/bin/containerd',              dest: '/bin/containerd' }
    - { src: '/tmp/containerd/bin/containerd-shim',         dest: '/bin/containerd-shim' }
    - { src: '/tmp/containerd/bin/containerd-shim-runc-v1', dest: '/bin/containerd-shim-runc-v1' }
    - { src: '/tmp/containerd/bin/containerd-shim-runc-v2', dest: '/bin/containerd-shim-runc-v2' }
    - { src: '/tmp/containerd/bin/ctr',                     dest: '/bin/ctr' }
