---
- name: Configure PKI (1/2) - Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true
  loop:
    - /var/lib/kubernetes

- name: Configure PKI (2/2) - Copy PKI keys and certificates
  ansible.builtin.copy:
    src: ../../../../../tls/{{ item }}
    dest: /var/lib/kubernetes/{{ item }}
    owner: root
    group: root
    mode: '0644'
  become: true
  loop:
    - ca.pem
    - ca-key.pem
    - kubernetes.pem
    - kubernetes-key.pem
    - service-account.pem
    - service-account-key.pem
    - encryption-config.yaml
