---
- name: Install kube-apiserver (1/3) - Download binary
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64/kube-apiserver
    dest: /usr/local/bin/kube-apiserver
    mode: '0755'
  become: true

- name: Install kube-apiserver (2/3) - Configure systemd unit
  ansible.builtin.template:
    src: templates/kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - Systemd daemon_reload

- name: Install kube-apiserver (3/3) - Enable and start service
  ansible.builtin.systemd_service:
    state: started
    name: kube-apiserver
    enabled: true
  become: true
