---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true
  loop:
    - /etc/kubernetes
    - /etc/kubernetes/config
    - /var/lib/kubernetes

- name: Download and unpack kubernetes control plane components
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64/{{ item }}
    dest: /usr/local/bin/{{ item }}
    mode: '0755'
  become: true
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubectl

- name: Copy PKI keys and certificates
  ansible.builtin.copy:
    src: ../../../../../tls/{{ item }}
    dest: /var/lib/kubernetes/{{ item }}
    owner: root
    group: root
    mode: '0644'
  become: true
  loop:
    - ca.pem
    - ca-key.pem
    - kubernetes.pem
    - kubernetes-key.pem
    - service-account.pem
    - service-account-key.pem
    - encryption-config.yaml

- name: Copy kubeconfigs
  ansible.builtin.copy:
    src: ../../../../../kubeconfig/{{ item }}
    dest: /var/lib/kubernetes/{{ item }}
    owner: root
    group: root
    mode: '0644'
  become: true
  loop:
    - kube-controller-manager.kubeconfig
    - kube-scheduler.kubeconfig

- name: Copy configurations
  ansible.builtin.copy:
    src: files/kube-scheduler.yaml
    dest: /etc/kubernetes/config/kube-scheduler.yaml
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Configure systemd units
  ansible.builtin.template:
    src: templates/{{ item }}.service.j2
    dest: /etc/systemd/system/{{ item }}.service
    owner: root
    group: root
    mode: '0644'
  become: true
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  notify:
    - Systemd daemon_reload

- name: Make sure service is running
  ansible.builtin.systemd_service:
    state: started
    name: "{{ item }}"
    enabled: true
  become: true
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
