---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  become: true

- name: Copy nginx config
  ansible.builtin.copy:
    src: kubernetes.default.svc.cluster.local
    dest: /etc/nginx/sites-available/kubernetes.default.svc.cluster.local
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Enable nginx config
  ansible.builtin.file:
    src: /etc/nginx/sites-available/kubernetes.default.svc.cluster.local
    dest: /etc/nginx/sites-enabled/kubernetes.default.svc.cluster.local
    owner: root
    group: root
    state: link
  become: true
  notify:
    - Restart nginx
