---
- name: Configure PKI
  ansible.builtin.include_tasks: configure-pki.yaml

- name: Install kube-apiserver
  ansible.builtin.include_tasks: install-and-configure-kube-apiserver.yaml

- name: Install kube-controller-manager
  ansible.builtin.include_tasks: install-and-configure-kube-controller-manager.yaml

- name: Install kube-scheduler
  ansible.builtin.include_tasks: install-and-configure-kube-scheduler.yaml

- name: Configure load balancer health checks
  ansible.builtin.include_tasks: load-balancer-health-checks.yaml
