TERRAFORM_PATH=aws

compute/all: compute/apply

compute/plan:
	cd ${TERRAFORM_PATH}; aws-profile -p root terraform init; aws-profile -p root terraform plan

compute/apply:
	cd ${TERRAFORM_PATH}; aws-profile -p root terraform apply -auto-approve

compute/clean:
	cd ${TERRAFORM_PATH}; aws-profile -p root terraform destroy -auto-approve
