TERRAFORM_PATH=aws

compute/all: compute/apply

compute/plan:
	cd ${TERRAFORM_PATH}; aws-profile -p management terraform init; aws-profile -p management terraform plan

compute/apply:
	cd ${TERRAFORM_PATH}; aws-profile -p management terraform apply -auto-approve

compute/clean:
	cd ${TERRAFORM_PATH}; aws-profile -p management terraform destroy -auto-approve
