---
- name: Configure hostname (1/3) - Set the hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
  become: true

- name: Configure hostname (2/3) - Ensure /etc/systemd/resolved.conf.d directory exists
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: '0755'
  become: true

- name: Configure hostname (3/3) - Add custom search domains configuration for systemd-resolved
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/custom_domains.conf
    content: |
      [Resolve]
      Domains=kthw.internal eu-west-1.compute.internal
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-resolved
  become: true
