---
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
  become: true

- name: Copy ca.pem
  ansible.builtin.copy:
    src: ../../../../tls/ca.pem
    dest: /home/ubuntu/ca.pem
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Copy admin kubeconfig
  ansible.builtin.copy:
    src: ../../../../../kubeconfig/admin.kubeconfig
    dest: /home/ubuntu/admin.kubeconfig
    owner: ubuntu
    group: ubuntu
    mode: '0644'
