---
# handlers file for common
- name: Systemd daemon_reload
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: yes
  become: true
