---
- name: Systemd daemon_reload
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: Copy binaries
  ansible.builtin.copy:
    src: /tmp/etcd-v{{ etcd_version }}-linux-amd64/{{ item }}
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  become: true
  ignore_errors: true
  loop:
    - etcd
    - etcdctl
