---
- name: Copy PKI keys and certificates
  ansible.builtin.copy:
    src: "../../../../../tls/{{ item }}"
    dest: "/home/ubuntu/{{ item }}"
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  loop:
    - kubernetes-key.pem
    - kubernetes.pem
    - service-account-key.pem
    - service-account.pem

- name: Copy kubeconfig
  ansible.builtin.copy:
    src: "../../../../../kubeconfig/{{ item }}"
    dest: "/home/ubuntu/{{ item }}"
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  loop:
    - admin.kubeconfig
    - kube-controller-manager.kubeconfig
    - kube-scheduler.kubeconfig
    - encryption-config.yaml
