---
- name: Install Etcd (1/5) - Create etcd directory
  ansible.builtin.file:
    path: /etc/etcd
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Install Etcd (2/5) - Copy PKI keys and certificates
  ansible.builtin.copy:
    src: ../../../../../tls/{{ item }}
    dest: /etc/etcd/{{ item }}
    owner: root
    group: root
    mode: '0644'
  become: true
  loop:
    - ca.pem
    - kubernetes-key.pem
    - kubernetes.pem

- name: Install Etcd (3/5) - Download and unpack release archive
  ansible.builtin.unarchive:
    src: https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0755'
    extra_opts: ['--strip-components=1', '--show-stored-names']
  become: true

- name: Install Etcd (4/5) - Configure systemd unit
  ansible.builtin.template:
    src: templates/etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - Systemd daemon_reload

- name: Install Etcd (5/5) - Make sure etcd is running
  ansible.builtin.systemd_service:
    state: started
    name: etcd
    enabled: true
  become: true
